Recetario/Models/ErrorViewModel.cs
using System;

namespace Recetario.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Recetario/Models/Receta.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Recetario.Models
{
    public class Receta
    {
        [Key] //Data Annotation que sirve para indicar que el atributo será la llave primaria
        public int Id { get; set; }
        //Data Annotation que sirve para establecer el largo de un tipo de texto, y adicionalmente configurado un mensage en caso de error
        [StringLength(255, ErrorMessage = "El largo máximo del campo es {0} carácteres.")]
        //DAta annotation para indicar que el campo es requerido en cualquier contexto.
        [Required]
        [DisplayName("Nombre de la Receta")]
        public string Nombre { get; set; }
        [StringLength(511, ErrorMessage = "El largo máximo del campo es {0} carácteres.")]
        [Required]
        [DisplayName("Descripción")]
        public string Descripcion { get; set; }

        [DisplayName("Preparada Anteriormente")]
        public bool EstaPreparada { get; set; }

        //si tuvvieramos un campo numérico(int, long, float, double)
        //[Range(1, 10)]

       
    }
}

Recetario/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Recetario.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Recetario.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Contacto()
        {

            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Recetario/Controllers/RecetaController.cs
using Microsoft.AspNetCore.Mvc;
using Recetario.Data;
using Recetario.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Recetario.Controllers
{
    public class RecetaController : Controller
    {
        private readonly ApplicationDbContext _db;

        public RecetaController(ApplicationDbContext db)
        {
            _db = db;
        }

        //GET - INDEX
        [HttpGet]
        public IActionResult Index()
        {
            //_db.Recetas;
            //List<Receta> recetas = new List<Receta>();
            IEnumerable<Receta> obj = _db.Recetas;
            return View(obj);
        }

        //GET - CREAR
        public IActionResult Crear()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Crear(Receta objeto)
        {
            if (ModelState.IsValid)
            {
                _db.Recetas.Add(objeto);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(objeto);

        }

        //GET - EDITAR
        public IActionResult Editar(int? id)
        {
            // || = OR
            // && = AND
            if(id == null || id == 0 || id < 0)
            {
                return NotFound();
            }

            Receta recetaActual = _db.Recetas.Find(id);

            if (recetaActual == null)
            {
                return NotFound();
            }

            return View(recetaActual);
        }

        //POST - EDITAR
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Editar(Receta objeto)
        {
            if (ModelState.IsValid)
            {
                _db.Recetas.Update(objeto);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(objeto);

        }

        //GET - ELIMINAR
        public IActionResult Eliminar(int? id)
        {
            // || = OR
            // && = AND
            if (id == null || id == 0 || id < 0)
            {
                return NotFound();
            }

            Receta recetaActual = _db.Recetas.Find(id);

            if (recetaActual == null)
            {
                return NotFound();
            }

            return View(recetaActual);
        }

        //POST - ELIMINAR
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EliminarAction(int? id)
        {
            if (id == null || id == 0 || id < 0)
            {
                return NotFound();
            }

            Receta recetaActual = _db.Recetas.Find(id);

            if (recetaActual == null)
            {
                return NotFound();
            }
            _db.Recetas.Remove(recetaActual);
            _db.SaveChanges();

            return RedirectToAction("Index");

        }
    }
}

Recetario/Controllers/TestController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Recetario.Controllers
{
    public class TestController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Recetario/Views/Home/Contacto.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div class="container">
    <div class="row">
        <div class="col-6">
            <h1>Estoy en la página Contacto</h1>
        </div>
        <div class="col-6">
            <p>Estoy experimentando con clases de bootsrap probando si funciona.</p>
        </div>
    </div>
</div>

Recetario/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Recetario/Views/Receta/Crear.cshtml
@model Recetario.Models.Receta

@{
    ViewData["Title"] = "Crear";
}

<h1>Crear</h1>

<h4>Receta</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Crear" method="post">

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>

            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="EstaPreparada" /> @Html.DisplayNameFor(model => model.EstaPreparada)
                </label>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>

        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Recetario/Views/Receta/Editar.cshtml
@model Recetario.Models.Receta

@{
    ViewData["Title"] = "Editar";
}

<h1>Editar</h1>

<h4>Receta</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Editar">

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <input type="hidden" asp-for="Id" />

            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>

            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="EstaPreparada" /> @Html.DisplayNameFor(model => model.EstaPreparada)
                </label>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>

        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Recetario/Views/Receta/Eliminar.cshtml
@model Recetario.Models.Receta

@{
    ViewData["Title"] = "Eliminar";
}

<h1>Eliminar</h1>

<h3>¿Estás seguro de que quieres borrar este registro?</h3>
<div>
    <h4>Receta</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EstaPreparada)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EstaPreparada)
        </dd>
    </dl>
    
    <form asp-action="EliminarAction">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Recetario/Views/Receta/Index.cshtml
@model IEnumerable<Receta>
@{
    ViewData["Title"] = "Index";
}


<div class="container">
    <div class="row">
        <div class="col-10">
            <h1>Recetas</h1>
        </div>
        <div class="col-2">
            <a asp-controller="Receta" asp-action="Crear" class="btn btn-success">
                Agregar Receta
            </a>
        </div>
    </div>
</div>

@if(Model.Count() > 0)
{
    <h3>Existen Recetas!</h3>


    <table border="1">
        <thead>
            <tr>
                <td>ID</td>
                <td>Nombre</td>
                <td>Descripción</td>
                <td>Está Preparado</td>
                <td>Opciones</td>
            </tr>
        </thead>

        <tbody>
            @foreach (var m in Model)
            {
                <tr>
                    <td>@m.Id</td>
                    <td>@m.Nombre</td>
                    <td>@m.Descripcion</td>
                    @if (m.EstaPreparada)
                    {
                        <td>Si</td>
                    }
                    else
                    {
                        <td>No</td>
                    }
                    <td>
                        <div class="btn-group-sm">
                            <a asp-controller="Receta" asp-action="Editar" asp-route-Id="@m.Id" role="button" class="btn btn-secondary btn-sm">Editar</a>
                            <a asp-controller="Receta" asp-action="Eliminar" asp-route-Id="@m.Id" role="button" class="btn btn-danger btn-sm">Borrar</a>

                        </div>
                    </td>
            </tr>
            }
        </tbody>
    </table>
}

Recetario/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Recetario</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-primary border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Recetario</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Contacto">Contacto</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Test" asp-action="Index">Test Index</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Receta" asp-action="Index">Lista de Recetas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Recetario - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Recetario/Views/Test/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>


<p>Actualmente me encuentro en la acción Index, del controlador Test. Creado en clases para mostrar
    un ejempolo en la creación de nuevas páginas/controladores/vistas, etc.</p>